# Generated by Django 4.2.6 on 2023-10-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
